# Generated by Django 3.2.4 on 2023-10-26 00:48

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Carrers',
            fields=[
                ('id', models.AutoField(db_column='idcarrers', primary_key=True, serialize=False)),
                ('name_carrer', models.CharField(db_column='name_carrer', max_length=200)),
            ],
            options={
                'db_table': 'carrers',
            },
        ),
        migrations.CreateModel(
            name='Course',
            fields=[
                ('id', models.AutoField(db_column='idcourse', primary_key=True, serialize=False)),
                ('type_course', models.CharField(db_column='type_course', max_length=200)),
            ],
            options={
                'db_table': 'course',
            },
        ),
        migrations.CreateModel(
            name='Group',
            fields=[
                ('id', models.AutoField(db_column='idgroup', primary_key=True, serialize=False)),
                ('group_name', models.CharField(db_column='group_name', max_length=100)),
                ('max_capacity_students', models.IntegerField(db_column='max_capacity_students', default=40)),
                ('fk_carrer', models.ForeignKey(db_column='fk_carrer', on_delete=django.db.models.deletion.CASCADE, to='api.carrers')),
            ],
            options={
                'db_table': 'groups',
            },
        ),
        migrations.CreateModel(
            name='Period',
            fields=[
                ('id', models.AutoField(db_column='idperiod', primary_key=True, serialize=False)),
                ('period_description', models.CharField(db_column='period_description', max_length=100)),
            ],
            options={
                'db_table': 'periods',
            },
        ),
        migrations.CreateModel(
            name='Students',
            fields=[
                ('id', models.AutoField(db_column='idstudents', primary_key=True, serialize=False)),
                ('name', models.CharField(db_column='name', max_length=200)),
                ('app', models.CharField(db_column='app', max_length=200)),
                ('apm', models.CharField(db_column='apm', max_length=200)),
                ('student_id', models.CharField(db_column='student_id', max_length=100)),
            ],
            options={
                'db_table': 'students',
            },
        ),
        migrations.CreateModel(
            name='GroupCourseUserStudents',
            fields=[
                ('id', models.AutoField(db_column='idGroupCourseUserStudent', primary_key=True, serialize=False)),
                ('fk_course', models.ForeignKey(db_column='fk_course', on_delete=django.db.models.deletion.CASCADE, to='api.course')),
                ('fk_group', models.ForeignKey(db_column='fk_group', on_delete=django.db.models.deletion.CASCADE, to='api.group')),
                ('fk_students', models.ForeignKey(db_column='fk_student', on_delete=django.db.models.deletion.CASCADE, to='api.students')),
                ('fk_user', models.ForeignKey(db_column='fk_user', on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'groupcourseuserstudents',
            },
        ),
        migrations.CreateModel(
            name='GroupCourseUser',
            fields=[
                ('id', models.AutoField(db_column='idGroupCourseUser', primary_key=True, serialize=False)),
                ('fk_course', models.ForeignKey(db_column='fk_course', on_delete=django.db.models.deletion.CASCADE, to='api.course')),
                ('fk_group', models.ForeignKey(db_column='fk_group', on_delete=django.db.models.deletion.CASCADE, to='api.group')),
                ('fk_user', models.ForeignKey(db_column='fk_user', on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'groupcourseuser',
            },
        ),
        migrations.AddField(
            model_name='group',
            name='fk_period',
            field=models.ForeignKey(db_column='fk_period', default=1, on_delete=django.db.models.deletion.CASCADE, to='api.period'),
        ),
        migrations.CreateModel(
            name='Attendance',
            fields=[
                ('id', models.AutoField(db_column='idattendance', primary_key=True, serialize=False)),
                ('attendance', models.IntegerField(db_column='attendance')),
                ('fk_group_course_user_student', models.ForeignKey(db_column='fk_group_course_user_student', on_delete=django.db.models.deletion.CASCADE, to='api.groupcourseuserstudents')),
            ],
            options={
                'db_table': 'attendance',
            },
        ),
        migrations.CreateModel(
            name='Activities',
            fields=[
                ('id', models.AutoField(db_column='idactivities', primary_key=True, serialize=False)),
                ('title', models.CharField(db_column='title', max_length=100)),
                ('descriptions', models.TextField(db_column='description')),
                ('date_activities', models.DateField(db_column='date_activities')),
                ('completed', models.BooleanField(db_column='completed')),
                ('color', models.CharField(db_column='color', max_length=50)),
                ('fk_user', models.ForeignKey(db_column='fk_user', on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'activities',
            },
        ),
    ]
