# Generated by Django 3.2.4 on 2023-09-03 18:41

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Carrers',
            fields=[
                ('id', models.AutoField(db_column='idCarrers', primary_key=True, serialize=False)),
                ('name_carrer', models.CharField(db_column='name_carrer', max_length=200)),
            ],
            options={
                'db_table': 'carrers',
            },
        ),
        migrations.CreateModel(
            name='Period',
            fields=[
                ('id', models.AutoField(db_column='idPeriod', primary_key=True, serialize=False)),
                ('period_description', models.CharField(db_column='period_description', max_length=100)),
            ],
            options={
                'db_table': 'periods',
            },
        ),
        migrations.CreateModel(
            name='Group',
            fields=[
                ('id', models.AutoField(db_column='idgroup', primary_key=True, serialize=False)),
                ('group_name', models.CharField(db_column='group_name', max_length=100)),
                ('max_capacity_students', models.IntegerField(db_column='max_capacity_students', default=40)),
                ('fk_carrer', models.ForeignKey(db_column='fk_carrer', on_delete=django.db.models.deletion.CASCADE, to='api.carrers')),
            ],
            options={
                'db_table': 'groups',
            },
        ),
        migrations.CreateModel(
            name='Activities',
            fields=[
                ('id', models.AutoField(db_column='idactivities', primary_key=True, serialize=False)),
                ('title', models.CharField(db_column='title', max_length=100)),
                ('descriptions', models.TextField(db_column='description')),
                ('date_activities', models.DateField(db_column='date_activities')),
                ('completed', models.BooleanField(db_column='completed')),
                ('color', models.CharField(db_column='color', max_length=50)),
                ('fk_user', models.ForeignKey(db_column='fk_user', on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'activities',
            },
        ),
    ]
