# Generated by Django 4.2.4 on 2023-09-03 00:37

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Group',
            fields=[
                ('id', models.IntegerField(db_column='idgroup', primary_key=True, serialize=False)),
                ('group_name', models.CharField(db_column='group_name', max_length=100)),
            ],
        ),
    ]
