# Generated by Django 4.2.4 on 2023-09-03 01:16

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='group',
            name='id',
            field=models.AutoField(db_column='idgroup', primary_key=True, serialize=False),
        ),
        migrations.AlterModelTable(
            name='group',
            table='group',
        ),
        migrations.CreateModel(
            name='Activities',
            fields=[
                ('id', models.AutoField(db_column='idactivities', primary_key=True, serialize=False)),
                ('title', models.CharField(db_column='title', max_length=100)),
                ('descriptions', models.TextField(db_column='description')),
                ('date_activites', models.DateField(db_column='date_activities')),
                ('completed', models.BooleanField(db_column='completed')),
                ('user', models.ForeignKey(db_column='fk_user', on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'activities',
            },
        ),
    ]
