# Generated by Django 3.2.4 on 2023-09-03 18:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='group',
            name='fk_period',
            field=models.ForeignKey(db_column='fk_period', default=1, on_delete=django.db.models.deletion.CASCADE, to='api.period'),
        ),
    ]
