# Generated by Django 3.2.4 on 2023-09-03 18:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_group_fk_period'),
    ]

    operations = [
        migrations.CreateModel(
            name='Course',
            fields=[
                ('id', models.AutoField(db_column='idcourse', primary_key=True, serialize=False)),
                ('type_course', models.CharField(db_column='type_course', max_length=200)),
            ],
            options={
                'db_table': 'course',
            },
        ),
        migrations.AlterField(
            model_name='carrers',
            name='id',
            field=models.AutoField(db_column='idcarrers', primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='period',
            name='id',
            field=models.AutoField(db_column='idperiod', primary_key=True, serialize=False),
        ),
    ]
