# Generated by Django 3.2.4 on 2023-09-03 19:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_auto_20230903_1258'),
    ]

    operations = [
        migrations.CreateModel(
            name='GroupCourse',
            fields=[
                ('id', models.AutoField(db_column='idGroupCourse', primary_key=True, serialize=False)),
                ('fk_course', models.ForeignKey(db_column='fk_course', on_delete=django.db.models.deletion.CASCADE, to='api.course')),
                ('fk_group', models.ForeignKey(db_column='fk_group', on_delete=django.db.models.deletion.CASCADE, to='api.group')),
            ],
            options={
                'db_table': 'groupcourse',
            },
        ),
    ]
