# Generated by Django 3.2.4 on 2023-09-03 19:17

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('api', '0004_groupcourse'),
    ]

    operations = [
        migrations.AddField(
            model_name='groupcourse',
            name='fk_user',
            field=models.ForeignKey(db_column='fk_user', default=2, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
