# Generated by Django 3.2.4 on 2023-09-03 19:27

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('api', '0005_groupcourse_fk_user'),
    ]

    operations = [
        migrations.CreateModel(
            name='GroupCourseUser',
            fields=[
                ('id', models.AutoField(db_column='idGroupCourse', primary_key=True, serialize=False)),
                ('fk_course', models.ForeignKey(db_column='fk_course', on_delete=django.db.models.deletion.CASCADE, to='api.course')),
                ('fk_group', models.ForeignKey(db_column='fk_group', on_delete=django.db.models.deletion.CASCADE, to='api.group')),
                ('fk_user', models.ForeignKey(db_column='fk_user', on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'groupcourseuser',
            },
        ),
        migrations.CreateModel(
            name='Students',
            fields=[
                ('id', models.AutoField(db_column='idstudents', primary_key=True, serialize=False)),
                ('name', models.CharField(db_column='name', max_length=200)),
                ('app', models.CharField(db_column='app', max_length=200)),
                ('apm', models.CharField(db_column='apm', max_length=200)),
                ('student_id', models.CharField(db_column='student_id', max_length=100)),
            ],
            options={
                'db_table': 'students',
            },
        ),
        migrations.DeleteModel(
            name='GroupCourse',
        ),
    ]
