# Generated by Django 3.2.4 on 2023-09-03 19:31

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('api', '0006_auto_20230903_1327'),
    ]

    operations = [
        migrations.CreateModel(
            name='GroupCourseUserStudents',
            fields=[
                ('id', models.AutoField(db_column='idGroupCourse', primary_key=True, serialize=False)),
                ('fk_course', models.ForeignKey(db_column='fk_course', on_delete=django.db.models.deletion.CASCADE, to='api.course')),
                ('fk_group', models.ForeignKey(db_column='fk_group', on_delete=django.db.models.deletion.CASCADE, to='api.group')),
                ('fk_students', models.ForeignKey(db_column='fk_student', on_delete=django.db.models.deletion.CASCADE, to='api.students')),
                ('fk_user', models.ForeignKey(db_column='fk_user', on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'groupcourseuserstudents',
            },
        ),
    ]
