# Generated by Django 3.2.4 on 2023-09-03 19:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0007_groupcourseuserstudents'),
    ]

    operations = [
        migrations.AlterField(
            model_name='groupcourseuser',
            name='id',
            field=models.AutoField(db_column='idGroupCourseUser', primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='groupcourseuserstudents',
            name='id',
            field=models.AutoField(db_column='idGroupCourseUserStudent', primary_key=True, serialize=False),
        ),
    ]
