# Generated by Django 3.2.4 on 2023-09-03 19:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0008_auto_20230903_1346'),
    ]

    operations = [
        migrations.CreateModel(
            name='Attendance',
            fields=[
                ('id', models.AutoField(db_column='idattendance', primary_key=True, serialize=False)),
                ('attendance', models.IntegerField(db_column='attendance')),
                ('fk_group_course_user_student', models.ForeignKey(db_column='fk_group_course_user_student', on_delete=django.db.models.deletion.CASCADE, to='api.groupcourseuserstudents')),
            ],
            options={
                'db_table': 'attendance',
            },
        ),
    ]
